name: ML Pipeline

on:
  push:
    branches: [ main ]

jobs:

  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Pull Data
        run: echo "dvc pull simulated"

      - name: Train Model
        run: python train.py

      - name: Upload model_info.txt
        uses: actions/upload-artifact@v4
        with:
          name: model-info
          path: model_info.txt

      - name: Upload MLflow Data
        uses: actions/upload-artifact@v4
        with:
          name: mlruns-data
          path: mlruns


  deploy:
    needs: validate
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download model_info.txt
        uses: actions/download-artifact@v4
        with:
          name: model-info

      - name: Download MLflow Data
        uses: actions/download-artifact@v4
        with:
          name: mlruns-data

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install MLflow
        run: pip install mlflow

      - name: Check Threshold
        run: python check_threshold.py

      - name: Mock Docker Build
        run: |
          docker build --build-arg RUN_ID=$(cat model_info.txt) -t my-model .
          echo "Docker image built successfully"